export const lists = {
  "The Word Within the Word List #18": [
    ["log", "reason"],
    ["phor", "carry"],
    ["loco", "place"],
    ["de", "down"],
    ["phobia", "fear"],
    ["schizo", "divide"],
    ["theo", "god"],
    ["curs", "run"],
    ["en", "good"],
    ["funi", "cord"],
    ["nym", "name"],
    ["ize", "make"],
    ["re", "again"],
    ["ambul", "walk"],
    ["ideo", "idea"],
    ["apo", "up"],
    ["pre", "before"],
    ["cosmo", "universe"],
    ["phon", "sound"],
    ["meta", "change"],
    ["syllogism", "three-part deduction"],
    ["metonymy", "association name"],
    ["anaphora", "repetition in successive phrases"],
    ["bowdlerize", "censor prudishly"],
    ["locus classicus", "classical example"],
    ["reiterate", "repeat"],
    ["desultory", "rambling"],
    ["funambulist", "tightrope walker"],
    ["lyssophobia", "fear of insanity"],
    ["idèe fixe", "obsession"],
    ["schism", "division"],
    ["apotheosis", "raising to god status"],
    ["precursor", "forerunner"],
    ["cosmology", "study of the universe"],
    ["euphony", "beautiful sound"]
  ],

  "The Word Within the Word List #17": [
    ["thanatos", "death"],
    ["opia", "sight"],
    ["vac", "empty"],
    ["luc", "light"],
    ["ize", "make"],
    ["sed", "sit"],
    ["fug", "flee"],
    ["pusill", "small"],
    ["nepo", "nephew"],
    ["viv", "life"],
    ["spir", "breathe"],
    ["syn", "together"],
    ["man", "hand"],  
    ["ex", "out"],
    ["ism", "system"],
    ["sub", "under"],
    ["ine", "nature of"],
    ["anim", "mind"],
    ["bon", "good"],
    ["ous", "full of"],
    ["thanatopsis", "view of death"],
    ["vacuous", "stupidly empty of ideas"],
    ["lucubration", "late studying"],
    ["ex cathedra", "from the throne"],
    ["legerdemain", "sleight of hand"],
    ["suspiration", "deep sigh"],
    ["nepotism", "favoritism to relatives"],
    ["synoptic", "general in view"],
    ["lionize", "treat as a celebrity"],
    ["assiduous", "persevering"],
    ["subterfuge", "evasive dodge"],
    ["bon vivant", "indulger in luxury"],
    ["saturnine", "gloomy and remote"],
    ["sedentary", "sitting"],
    ["pusillanimous", "small-minded"]
  ]
};
